### ISSUE TITLE
1.7.0.1.0 Release

### ISSUE THREAD

**Issue by sandroboehme** [marceloverdijk/lesscss-java#48]
As promised I'm now working on syncing my fork (`de.sandroboehme.lesscss:lesscss:1.6.1.1.0` from https://github.com/sandroboehme/lesscss-java) back to this project.

The next version will be `org.lesscss:lesscss:1.7.0.1.0` as it is the 1.0 release for less 1.7.0 (Rhino based).

The currently pushed code fixes the following issues:
- Less 1.7.0 support
- #42 (Add ability to use any parameter supported by less.js)
- #43 (Bootstrap 3.1 vs. Less 1.6.x)
- https://github.com/sandroboehme/lesscss-maven-plugin/issues/1 (Error message in the output and not in the Exception)
  This last issue is currently fixed directly in the `rhino-lessc.js` file. But the fix has been committed to `less.js` in https://github.com/less/less.js/pull/1956. In the next release of `rhino-lessc.js` it should be included and no manual fix should be needed.
- #15 (Added shading for commons.io)
  This rewrites `org.apache.commons.io` to `org.lesscss.deps.org.apache.commons.io`.
  It avoids problems for projects that use that library in other versions. Please see #15 for details and discussion.

You can now test the code by running the automatic tests and by installing and trying it. Please let me know if everything works fine or if there are problems that prevent a release. I will not start a release in the next week to provide time for testing.

Best,

Sandro

**Comment by davidmc24** [comment]
In one of my comments on #15, I'd suggested the following, which perhaps were overlooked.  I know it's been a while since that conversation.
- Change the `shadedPattern` from `internalDeps.*` to `de.sandroboehme.lesscss.deps.*`.  This avoids conflicts with other libraries that are using shading, and better reflects that these are _our_ dependencies, not general dependencies to be used by anyone.
- Don't shade `slf4j-api`.  Currently, I believe that the approach taken by `lesscss-java` is to use SLF4J if it's available, and use JULI logging if it isn't.  Shading SLF4J breaks this.

**Comment by sandroboehme** [comment]
Fixed in the code and in my initial comment above.
Thanks for the reminder David!

**Comment by codler** [comment]
Great work!

**Comment by sandroboehme** [comment]
Thanks!

**Comment by sandroboehme** [comment]
The release is available now. 
http://search.maven.org/#search|ga|1|org.lesscss
Enjoy!
